apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hello-kubernetes
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8030 # port Service di dalam cluster. Semua Pod lain atau aplikasi internal cluster akan mengakses Service melalui port ini
      targetPort: 8030 # Port tempat layanan Spring Boot berjalan (server.port=8080)
      nodePort: 30030 # Ini adalah port di node Kubernetes (host machine minikube). Digunakan ketika Service type = NodePort. Akses dari luar cluster menggunakan port ini
