apiVersion: v1
kind: Service
metadata:
  name: spring-hello
  namespace: hello-kubernetes
spec:
  type: NodePort
  selector:
    app: spring-hello
  ports:
    - port: 8080 # port Service di dalam cluster. Semua Pod lain atau aplikasi internal cluster akan mengakses Service melalui port ini
      targetPort: 8080 # Port tempat layanan Spring Boot berjalan (server.port=8080)
      nodePort: 30080 # Ini adalah port di node Kubernetes (host machine minikube). Digunakan ketika Service type = NodePort. Akses dari luar cluster menggunakan port ini
